VAGRANTFILE_API_VERSION = '2'

Vagrant.configure VAGRANTFILE_API_VERSION do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 's13t245'
  config.vm.network :public_network, ip: '192.168.11.47', bridge: 'eth1'

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  config.vm.provision 'ansible' do |ansible|
    ansible.playbook = './apache.yml'
  end
end
