VAGRANTFILE_API_VERSION = '2'

Vagrant.configure VAGRANTFILE_API_VERSION do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 's00t000'
  config.vm.network :public_network, ip: '192.168.11.40', bridge: 'eth1'

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # config.vm.provision :ansible do |ansible|
  #   ansible.playbook = '../ansible/main.yml'
  # end

  config.vm.provision :itamae do |itamae|
    itamae.sudo = true
    ansible.recipes = ['../itamae/default.rb']
  end
end
