VAGRANTFILE_API_VERSION = '2'

Vagrant.configure VAGRANTFILE_API_VERSION do |config|
  config.vm.box = 'ubuntu/trusty64'
  config.vm.hostname = 's13t232'
  config.vm.network :public_network, ip: '192.168.11.48', bridge: 'eth1'

  config.vm.provider :virtualbox do |v|
    v.memory = 1024
    v.cpus = 1
  end

  # config.vm.provision 'ansible' do |ansible|
  #   ansible.playbook = 'apache.yml'
  # end

  config.vm.provision :itamae do |itamae|
    itamae.sudo = true
    itamae.shell = '/bin/sh'
    itamae.recipes = ['ruby.rb']
    itamae.json = 'ruby.json'
  end
end
